"""Initial migration

Revision ID: 209a06a28773
Revises: 
Create Date: 2025-12-15 17:13:35.393082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209a06a28773'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_name', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('img', sa.String(length=128), nullable=False),
    sa.Column('_description', sa.Text(), nullable=True),
    sa.Column('_tags', sa.Text(), nullable=True),
    sa.Column('new_window', sa.Boolean(), nullable=True),
    sa.Column('frontend_only', sa.Boolean(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###
