"""Add theme and language click tracking columns

Revision ID: 45ebb5ba01b4
Revises: 70d6e86fe36e
Create Date: 2026-01-25 10:31:46.088445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ebb5ba01b4'
down_revision = '70d6e86fe36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('light_clicks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dark_clicks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('high_contrast_clicks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('en_clicks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('de_clicks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_column('de_clicks')
        batch_op.drop_column('en_clicks')
        batch_op.drop_column('high_contrast_clicks')
        batch_op.drop_column('dark_clicks')
        batch_op.drop_column('light_clicks')

    # ### end Alembic commands ###
