"""Add mobile_clicks and desktop_clicks to Link model

Revision ID: 51510669d76e
Revises: e5d05af4d2c9
Create Date: 2026-01-29 07:53:44.110880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51510669d76e'
down_revision = 'e5d05af4d2c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_clicks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('desktop_clicks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_column('desktop_clicks')
        batch_op.drop_column('mobile_clicks')

    # ### end Alembic commands ###
