"""Add system_theme_clicks column

Revision ID: 581726bafc8f
Revises: 45ebb5ba01b4
Create Date: 2026-01-25 10:37:28.365741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581726bafc8f'
down_revision = '45ebb5ba01b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_theme_clicks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_column('system_theme_clicks')

    # ### end Alembic commands ###
