"""Add uses_external_service to Link model

Revision ID: 6fac0baa9279
Revises: 209a06a28773
Create Date: 2025-12-18 13:07:49.713725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fac0baa9279'
down_revision = '209a06a28773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uses_external_service', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_column('uses_external_service')

    # ### end Alembic commands ###
