"""Add bot_click_count to Link model

Revision ID: 70d6e86fe36e
Revises: 6fac0baa9279
Create Date: 2026-01-16 08:45:36.115612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d6e86fe36e'
down_revision = '6fac0baa9279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_click_count', sa.Integer(), nullable=True))

    # Reset click_count to 0 since previous counts were mixed bot/human
    op.execute("UPDATE link SET click_count = 0")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_column('bot_click_count')

    # ### end Alembic commands ###
