"""Add bytes_served, bot_bytes_served, and is_meta_link to Link model

Revision ID: e5d05af4d2c9
Revises: 581726bafc8f
Create Date: 2026-01-28 17:30:35.037995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d05af4d2c9'
down_revision = '581726bafc8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bytes_served', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('bot_bytes_served', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('is_meta_link', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_column('is_meta_link')
        batch_op.drop_column('bot_bytes_served')
        batch_op.drop_column('bytes_served')

    # ### end Alembic commands ###
